# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86a4be3a7c8276ea07ed7e4ee4fed9866d81cb5eb5d5b2c3b478ec9fb03322828fbd35b133dcecda7fd2b46d3d44235ff2088d50185ac6fdad6a983234167a7d

test:
  secret_key_base: e4159e2317b35962d78d2549f9138e1c68989c943b817a4f4abb9a240ad1c8892c5d1939716c2e0e8ebe6434f8943185ba085d11db40274e0b8bc6ef6e29c241

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
